package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    dependencies {
        expect(RelativeId("Dep")) {
            snapshot {
                reuseBuilds = ReuseBuilds.NO
            }

            artifacts {
                artifactRules = "aaa"
            }
        }
        update(RelativeId("Dep")) {
            snapshot {
                reuseBuilds = ReuseBuilds.NO
                synchronizeRevisions = false
            }

            artifacts {
                artifactRules = "aaa"
            }
        }

    }
}
